### ISSUE TITLE
Multi Cursor Select Down Makes Cursor Go Away

### ISSUE THREAD

**Issue by wwells-apixio** [benmatselby/obsidian-multi-cursor#105]
Installed the plugin today and all of the features work except for one. When I try to place cursors on multiple lines in the down direction, all cursors are removed. I can get a single cursor back by double clicking. Up direction works fine. Not sure what is going on with that one :/

**Comment by benmatselby** [comment]
Hey @wwells-apixio , thanks for raising. Can you give me some details on what version of Obsidian you're using please, and what OS etc. I cannot currently replicate this.

**Comment by wwells-apixio** [comment]
Thanks for replying @benmatselby,

I am using Obsidian 0.14.6 for MacOS
MacOS 12.3.1 (21E258)

The versions.json from plugin (installed under .obsidian/plugins):
```
{
  "0.0.1": "0.13.0",
  "0.0.2": "0.13.0",
  "0.0.3": "0.13.0"
}
```

Hotkeys.json
```
{
  "obsidian-multi-cursor:add-cursor-above": [
    {
      "modifiers": [
        "Alt",
        "Mod"
      ],
      "key": "ArrowUp"
    }
  ],
  "obsidian-multi-cursor:add-cursors-to-selection": [
    {
      "modifiers": [
        "Alt",
        "Mod"
      ],
      "key": "I"
    }
  ],
  "obsidian-multi-cursor:duplicate-line-above": [
    {
      "modifiers": [
        "Alt",
        "Mod"
      ],
      "key": "A"
    }
  ],
  "obsidian-multi-cursor:duplicate-line-below": [
    {
      "modifiers": [
        "Alt",
        "Mod"
      ],
      "key": "B"
    }
  ],
  "obsidian-multi-cursor:add-cursor-below": [
    {
      "modifiers": [
        "Alt",
        "Mod"
      ],
      "key": "ArrowDown"
    }
  ]
}
```
1. I use the atom theme
2. No other community plugins

**Comment by benmatselby** [comment]
@wwells-apixio I've updated all the dependencies on the main branch. Can you check again please? I'm currently unable to replicate this issue 😞

**Comment by benmatselby** [comment]
Closing down, due to inactivity.
