### ISSUE TITLE
Duplicate extension?

### ISSUE THREAD

**Issue by huyz** [benmatselby/obsidian-multi-cursor#221]
Are you aware of https://github.com/SkepticMystic/advanced-cursors ?
Maybe the two efforts could merge?

**Comment by benmatselby** [comment]
Hey @huyz - Thanks for raising the ticket. I am aware. I believe that plugin is an official community plugin.. I wanted to learn something new, so I built this..  It's not listed as a community plugin, and I keep it ticking over.
