### ISSUE TITLE
Publish to Obsidian Community plugin

### ISSUE THREAD

**Issue by Chouffy** [benmatselby/obsidian-multi-cursor#288]
Hi!

Thanks for this plug-in, it's really nice!
Do you think you could publish it to [Obsidian Plugin](https://obsidian.md/plugins)?
I would make easier to install & update it.

Thanks!

**Comment by benmatselby** [comment]
Hey there @Chouffy 

I've tried before, but there is other plugins that are very similar, so it was not accepted. Apologies for this.
