### ISSUE TITLE
How to install manually on windows ?

### ISSUE THREAD

**Issue by Xiarno** [benmatselby/obsidian-multi-cursor#50]
I'm not sure how to clone a repo nor run the command to be able to install it.
How do I do it ? How do I install the plugins ?

**Comment by benmatselby** [comment]
Hey @Xiarno 

I don't run or really know Windows so I'm not sure. I wonder if [this link from GitHub would help](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository)? You will also then need [Node and npm installing](https://nodejs.org/en/download/).

There are other plugins in Obsidian that give similar support, if you want to use those instead. There would be less installation overhead. A good one to try out would be [Advanced Cursors](https://github.com/SkepticMystic/advanced-cursors).

**Comment by sylumer** [comment]
FWIW, I used the Obsidian42-BRAT plugin (available in the app's community plugin list), added this GitHub Repo, and within a few moments I had the Obsidian Multi-Cursor plugin installed. I enabled it, and so far it is running just fine on Windows. 

_So nice to be able to do the cursor on each line in the selection - something I use all the time in my code editor._

**Comment by benmatselby** [comment]
That's great to hear @sylumer. Do you mind me closing this issue down?
